import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

dotenv.config({ path: join(__dirname, '..', '.env') });

const prisma = new PrismaClient();

const pistasNormalizadas = [
  {
    tipo: 'ALBUM',
    respuesta: 'YHLQMDLG',
    artista: 'Bad Bunny',
    respuestasAceptadas: ['YHLQMDLG', 'Yo Hago Lo Que Me Da La Gana'],
    pistaAnio: 2020,
    pistaGenero: 'Reggaeton',
    pistaCanciones: ['La Santa', 'Bichiyal', 'Safaera', 'Pero Ya No'],
    pistaColaboradores: ['Daddy Yankee', 'Sech', 'Jowell & Randy', 'Yaviah'],
    pistaAdjetivos: ['Nocturno', 'Energico', 'Comercial', 'Puertorriqueno'],
    dificultad: 2,
  },
  {
    tipo: 'ALBUM',
    respuesta: 'Un Verano Sin Ti',
    artista: 'Bad Bunny',
    respuestasAceptadas: ['Un Verano Sin Ti', 'UVST'],
    pistaAnio: 2022,
    pistaGenero: 'Reggaeton',
    pistaCanciones: ['Titi Me Pregunto', 'Moscow Mule', 'Ojitos Lindos', 'Me Porto Bonito'],
    pistaColaboradores: ['Bomba Estereo', 'Buscabulla', 'Chencho Corleone', 'Rauw Alejandro'],
    pistaAdjetivos: ['Veraniego', 'Playero', 'Nostalgico', 'Versatil'],
    dificultad: 2,
  },
  {
    tipo: 'ALBUM',
    respuesta: 'DATA',
    artista: 'Tainy',
    respuestasAceptadas: ['DATA'],
    pistaAnio: 2023,
    pistaGenero: 'Reggaeton',
    pistaCanciones: ['obstaculo', '4U', 'Pasiempre', 'Sci-Fi'],
    pistaColaboradores: ['Bad Bunny', 'J Balvin', 'Mora', 'Young Miko', 'Sech', 'Arcangel'],
    pistaAdjetivos: ['Futurista', 'Produccion', 'Electronico', 'Conceptual'],
    dificultad: 3,
  },
  {
    tipo: 'ALBUM',
    respuesta: 'Vibras',
    artista: 'J Balvin',
    respuestasAceptadas: ['Vibras'],
    pistaAnio: 2018,
    pistaGenero: 'Reggaeton',
    pistaCanciones: ['Ambiente', 'No Es Justo', 'Machika', 'Ahora'],
    pistaColaboradores: ['Carla Morrison', 'Rosalia', 'Willy William'],
    pistaAdjetivos: ['Luminoso', 'Global', 'Suave', 'Colorido'],
    dificultad: 2,
  },
  {
    tipo: 'ALBUM',
    respuesta: 'OASIS',
    artista: 'J Balvin / Bad Bunny',
    respuestasAceptadas: ['OASIS', 'Oasis'],
    pistaAnio: 2019,
    pistaGenero: 'Reggaeton',
    pistaCanciones: ['Que Pretendes', 'La Cancion', 'Yo Le Llego', 'Cuidao Por Ahi'],
    pistaColaboradores: ['J Balvin', 'Bad Bunny'],
    pistaAdjetivos: ['Colaborativo', 'Corto', 'Experimental', 'Puertorriqueno'],
    dificultad: 2,
  },
  {
    tipo: 'ALBUM',
    respuesta: 'SATURNO',
    artista: 'Rauw Alejandro',
    respuestasAceptadas: ['SATURNO', 'Saturno'],
    pistaAnio: 2022,
    pistaGenero: 'Reggaeton',
    pistaCanciones: ['Punto 40', 'Lejos del Cielo', 'Cuki', 'MORE'],
    pistaColaboradores: ['Baby Rasta', 'Quevedo'],
    pistaAdjetivos: ['Futurista', 'Espacial', 'Sintetizador', 'Perreo'],
    dificultad: 2,
  },
  {
    tipo: 'ALBUM',
    respuesta: 'El Madrileno',
    artista: 'C. Tangana',
    respuestasAceptadas: ['El Madrileno', 'El Madrileño'],
    pistaAnio: 2021,
    pistaGenero: 'Urbano',
    pistaCanciones: ['Demasiadas Mujeres', 'Tu Me Dejaste de Querer', 'Comerte Entera', 'Ingobernable'],
    pistaColaboradores: ['Kiko Veneno', 'Jorge Drexler', 'Toquinho', 'Omar Apollo'],
    pistaAdjetivos: ['Castizo', 'Orquestal', 'Folk', 'Espanol'],
    dificultad: 3,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Safaera',
    artista: 'Bad Bunny',
    respuestasAceptadas: ['Safaera'],
    pistaAnio: 2020,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'YHLQMDLG',
    pistaColaboradores: ['Jowell & Randy', 'Ñengo Flow'],
    pistaAdjetivos: ['Clasico', 'Perreo', 'Energetico', 'Largo'],
    dificultad: 1,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Titi Me Pregunto',
    artista: 'Bad Bunny',
    respuestasAceptadas: ['Titi Me Pregunto', 'Titi'],
    pistaAnio: 2022,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'Un Verano Sin Ti',
    pistaAdjetivos: ['Veraniego', 'Bailable', 'Popular', 'Global'],
    dificultad: 1,
  },
  {
    tipo: 'CANCION',
    respuesta: 'BICHOTA',
    artista: 'KAROL G',
    respuestasAceptadas: ['BICHOTA', 'Bichota'],
    pistaAnio: 2020,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'KG0516',
    pistaAdjetivos: ['Empoderamiento', 'Perreo', 'Colombiano', 'Hit'],
    dificultad: 1,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Provenza',
    artista: 'KAROL G',
    respuestasAceptadas: ['PROVENZA', 'Provenza'],
    pistaAnio: 2022,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'MANANA SERA BONITO',
    pistaAdjetivos: ['Melodico', 'Viaje', 'Colombiano', 'Romantico'],
    dificultad: 1,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Gasolina',
    artista: 'Daddy Yankee',
    respuestasAceptadas: ['Gasolina'],
    pistaAnio: 2004,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'Barrio Fino',
    pistaAdjetivos: ['Clasico', 'Leyenda', 'Puertorriqueno', 'Pionero'],
    dificultad: 1,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Dile',
    artista: 'Don Omar',
    respuestasAceptadas: ['Dile'],
    pistaAnio: 2005,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'The Last Don 2',
    pistaAdjetivos: ['Clasico', 'Romantico', 'Puertorriqueno', 'Pionero'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Felices los 4',
    artista: 'Maluma',
    respuestasAceptadas: ['Felices los 4', 'Felices Los 4'],
    pistaAnio: 2017,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'F.A.M.E.',
    pistaAdjetivos: ['Romantico', 'Colombiano', 'Popular', 'Melodico'],
    dificultad: 1,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Mi Gente',
    artista: 'J Balvin',
    respuestasAceptadas: ['Mi Gente'],
    pistaAnio: 2017,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'Vibras',
    pistaColaboradores: ['Willy William'],
    pistaAdjetivos: ['Global', 'Colombiano', 'Bailable', 'Hit'],
    dificultad: 1,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Mala Mujer',
    artista: 'C. Tangana',
    respuestasAceptadas: ['Mala Mujer'],
    pistaAnio: 2016,
    pistaGenero: 'Trap',
    pistaAlbum: 'Antes de Morirme',
    pistaAdjetivos: ['Trap', 'Espanol', 'Clasico', 'Urbano'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Columbia',
    artista: 'Quevedo',
    respuestasAceptadas: ['Columbia'],
    pistaAnio: 2023,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'DONDE QUIERO ESTAR',
    pistaAdjetivos: ['Canario', 'Melodico', 'Hit', 'Moderno'],
    dificultad: 1,
  },
  {
    tipo: 'CANCION',
    respuesta: 'PUNTO G',
    artista: 'Quevedo',
    respuestasAceptadas: ['PUNTO G', 'Punto G'],
    pistaAnio: 2023,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'DONDE QUIERO ESTAR',
    pistaAdjetivos: ['Canario', 'Perreo', 'Sensual', 'Moderno'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Goteo',
    artista: 'DUKI',
    respuestasAceptadas: ['Goteo'],
    pistaAnio: 2019,
    pistaGenero: 'Trap',
    pistaAlbum: 'Desde el Fin del Mundo',
    pistaAdjetivos: ['Trap', 'Argentino', 'Calle', 'Duro'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Givenchy',
    artista: 'DUKI',
    respuestasAceptadas: ['GIVENCHY', 'Givenchy'],
    pistaAnio: 2022,
    pistaGenero: 'Trap',
    pistaAlbum: 'Temporada de Reggaeton 2',
    pistaAdjetivos: ['Trap', 'Argentino', 'Lujo', 'Duro'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Dance Crip',
    artista: 'Trueno',
    respuestasAceptadas: ['DANCE CRIP', 'Dance Crip'],
    pistaAnio: 2022,
    pistaGenero: 'Trap',
    pistaAlbum: 'BIEN O MAL',
    pistaAdjetivos: ['Trap', 'Argentino', 'Barrio', 'Energetico'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Mamichula',
    artista: 'Trueno',
    respuestasAceptadas: ['Mamichula'],
    pistaAnio: 2021,
    pistaGenero: 'Trap',
    pistaAlbum: 'Atrevido',
    pistaColaboradores: ['Nicki Nicole', 'Bizarrap'],
    pistaAdjetivos: ['Trap', 'Argentino', 'Melodico', 'Romantico'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Entre Nosotros',
    artista: 'Tiago PZK',
    respuestasAceptadas: ['Entre Nosotros', 'Entre Nosotros Remix'],
    pistaAnio: 2021,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'Portales',
    pistaColaboradores: ['Lit Killah', 'Nicki Nicole', 'Maria Becerra'],
    pistaAdjetivos: ['Argentino', 'Romantico', 'Popular', 'Melodico'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Classy 101',
    artista: 'Feid / Young Miko',
    respuestasAceptadas: ['CLASSY 101', 'Classy 101'],
    pistaAnio: 2023,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'MOR NO LE TEMES A LA OSCURIDAD',
    pistaAdjetivos: ['Colombiano', 'Puertorriqueno', 'Suave', 'Fino'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Normal',
    artista: 'Feid',
    respuestasAceptadas: ['Normal'],
    pistaAnio: 2023,
    pistaGenero: 'Reggaeton',
    pistaAlbum: 'FERXXOCALIPSIS',
    pistaAdjetivos: ['Colombiano', 'Romantico', 'Perreo', 'Suave'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Una Noche en Medellin',
    artista: 'Cris Mj',
    respuestasAceptadas: ['Una Noche en Medellin'],
    pistaAnio: 2022,
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Chileno', 'Perreo', 'Popular', 'Calle'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Gata Only',
    artista: 'FloyyMenor / Cris Mj',
    respuestasAceptadas: ['Gata Only'],
    pistaAnio: 2024,
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Chileno', 'Perreo', 'Viral', 'Moderno'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'La Bebe',
    artista: 'Yng Lvcas / Peso Pluma',
    respuestasAceptadas: ['La Bebe', 'La Bebe Remix'],
    pistaAnio: 2023,
    pistaGenero: 'Reggaeton',
    pistaColaboradores: ['Peso Pluma'],
    pistaAdjetivos: ['Mexicano', 'Regional', 'Perreo', 'Popular'],
    dificultad: 2,
  },
  {
    tipo: 'CANCION',
    respuesta: 'Debo Entender',
    artista: 'Santa Fe Klan',
    respuestasAceptadas: ['Debo Entender'],
    pistaAnio: 2021,
    pistaGenero: 'Rap',
    pistaAlbum: 'Bendecido',
    pistaAdjetivos: ['Mexicano', 'Rap', 'Calle', 'Emocional'],
    dificultad: 3,
  },
  {
    tipo: 'CANCION',
    respuesta: 'M.A.I',
    artista: 'Milo J',
    respuestasAceptadas: ['M.A.I', 'MAI', 'M A I'],
    pistaAnio: 2023,
    pistaGenero: 'Trap',
    pistaAdjetivos: ['Argentino', 'Joven', 'Melodico', 'Rap'],
    dificultad: 3,
  },
  {
    tipo: 'CANCION',
    respuesta: 'DUMBAI',
    artista: 'CA7RIEL & Paco Amoroso',
    respuestasAceptadas: ['DUMBAI', 'Dumbai'],
    pistaAnio: 2023,
    pistaGenero: 'Trap',
    pistaAlbum: 'BAÑO MARIA',
    pistaAdjetivos: ['Argentino', 'Experimental', 'Rave', 'Teatro'],
    dificultad: 3,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Bad Bunny',
    artista: 'Bad Bunny',
    respuestasAceptadas: ['Bad Bunny', 'Benito', 'Benito Antonio Martinez Ocasio'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Puertorriqueno', 'Global', 'Superstar', 'Versatil', 'Lider'],
    dificultad: 1,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Karol G',
    artista: 'Karol G',
    respuestasAceptadas: ['Karol G', 'KAROL G', 'Carolina Giraldo Navarro'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Colombiana', 'Global', 'Reina', 'Poderosa', 'Melodica'],
    dificultad: 1,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'J Balvin',
    artista: 'J Balvin',
    respuestasAceptadas: ['J Balvin', 'Jose Balvin', 'Jose Alvaro Osorio Balvin'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Colombiano', 'Global', 'Colorido', 'Pionero', 'Visionario'],
    dificultad: 1,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Feid',
    artista: 'Feid',
    respuestasAceptadas: ['Feid', 'Ferxxo', 'Salomon Villada Hoyos'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Colombiano', 'Ferxxo', 'Verde', 'Madrugada', 'Culto'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Rauw Alejandro',
    artista: 'Rauw Alejandro',
    respuestasAceptadas: ['Rauw Alejandro', 'Rauw', 'Raul Alejandro Ocasio Ruiz'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Puertorriqueno', 'Bailarin', 'Sensual', 'Fino', 'Espacial'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Quevedo',
    artista: 'Quevedo',
    respuestasAceptadas: ['Quevedo', 'Pedro Luis Dominguez Quevedo'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Canario', 'Melodico', 'Joven', 'Estrella', 'Versatil'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Duki',
    artista: 'Duki',
    respuestasAceptadas: ['Duki', 'Mauro Lombardo'],
    pistaGenero: 'Trap',
    pistaAdjetivos: ['Argentino', 'Duro', 'Trap', 'Lider', 'Calle'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'C. Tangana',
    artista: 'C. Tangana',
    respuestasAceptadas: ['C. Tangana', 'Anton Alvarez', 'Pucho', 'Anton Alvarez Alfaro'],
    pistaGenero: 'Urbano',
    pistaAdjetivos: ['Espanol', 'Madrileno', 'Innovador', 'Conceptual', 'Versatil'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Bad Gyal',
    artista: 'Bad Gyal',
    respuestasAceptadas: ['Bad Gyal', 'Alba Farelo'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Catalana', 'Dancehall', 'Autotune', 'Femenino', 'Poderosa'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Nicki Nicole',
    artista: 'Nicki Nicole',
    respuestasAceptadas: ['Nicki Nicole', 'Nicole Denise Cucco'],
    pistaGenero: 'Trap',
    pistaAdjetivos: ['Argentina', 'Joven', 'Femenino', 'Suave', 'Melodica'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Trueno',
    artista: 'Trueno',
    respuestasAceptadas: ['Trueno', 'Mateo Palacios Corazzina'],
    pistaGenero: 'Trap',
    pistaAdjetivos: ['Argentino', 'Joven', 'Barras', 'Fuego', 'Campeon'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Tiago PZK',
    artista: 'Tiago PZK',
    respuestasAceptadas: ['Tiago PZK', 'Tiago Uriel Pacheco'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Argentino', 'Joven', 'Romantico', 'Popular', 'Melodico'],
    dificultad: 3,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Young Miko',
    artista: 'Young Miko',
    respuestasAceptadas: ['Young Miko', 'Maria Victoria Ramirez De Arellano'],
    pistaGenero: 'Trap',
    pistaAdjetivos: ['Puertorriquena', 'Lesbiana', 'Autentica', 'Fresca', 'Cool'],
    dificultad: 3,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Eladio Carrion',
    artista: 'Eladio Carrion',
    respuestasAceptadas: ['Eladio Carrion', 'Eladio'],
    pistaGenero: 'Trap',
    pistaAdjetivos: ['Puertorriqueno', 'Humor', 'Barras', 'Tecnico', 'Versatil'],
    dificultad: 3,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Mora',
    artista: 'Mora',
    respuestasAceptadas: ['Mora', 'Gabriel Armando Mora Quintero'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Puertorriqueno', 'Suave', 'Melodico', 'Perreo', 'Neblina'],
    dificultad: 3,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Myke Towers',
    artista: 'Myke Towers',
    respuestasAceptadas: ['Myke Towers', 'Michael Anthony Torres Monge'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Puertorriqueno', 'Melodico', 'Calle', 'Versatil', 'Trabajador'],
    dificultad: 3,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Anuel AA',
    artista: 'Anuel AA',
    respuestasAceptadas: ['Anuel AA', 'Emmanuel Gazmey Santiago', 'Anuel'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Puertorriqueno', 'Real Hasta La Muerte', 'Duro', 'Pionero', 'Controversial'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Ozuna',
    artista: 'Ozuna',
    respuestasAceptadas: ['Ozuna', 'Juan Carlos Ozuna Rosado', 'El Negrito Ojos Claros'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Puertorriqueno', 'Melodico', 'Romantico', 'Popular', 'Ojos Claros'],
    dificultad: 2,
  },
  {
    tipo: 'ARTISTA',
    respuesta: 'Daddy Yankee',
    artista: 'Daddy Yankee',
    respuestasAceptadas: ['Daddy Yankee', 'Ramon Luis Ayala Rodriguez', 'El Maximo Lider', 'King Daddy'],
    pistaGenero: 'Reggaeton',
    pistaAdjetivos: ['Puertorriqueno', 'Leyenda', 'Pionero', 'Gasolina', 'Maximo Lider'],
    dificultad: 1,
  },
];

async function seed() {
  console.log('Iniciando seed de Quavedle...');

  for (const pista of pistasNormalizadas) {
    try {
      await prisma.pistaQuavedle.upsert({
        where: {
          id: `${pista.tipo.toLowerCase()}_${pista.respuesta.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '')}`,
        },
        update: pista,
        create: {
          id: `${pista.tipo.toLowerCase()}_${pista.respuesta.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '')}`,
          ...pista,
        },
      });
      console.log(`✓ ${pista.tipo}: ${pista.respuesta}`);
    } catch (error) {
      console.error(`✗ Error en ${pista.respuesta}:`, error.message);
    }
  }

  console.log(`\nSeed completado. ${pistasNormalizadas.length} pistas insertadas.`);
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });